# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

commands:
  install-dependencies:
    # Install NPM dependencies quickly using "npm ci"
    # https://on.cypress.io/continuous-integration
    # https://docs.npmjs.com/cli/ci
    description: installs npm dependencies
    steps:
      # Install NPM dependencies quickly
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install TodoMVC dependencies
          command: npm ci
          working_directory: todomvc
      - run:
          name: Install TodoMVC Redux dependencies
          command: npm ci
          working_directory: todomvc-redux

jobs:
  # example test job with 2 commands
  # 1. starts the app in the background
  # 2. runs the tests in a separate command
  two-commands:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - install-dependencies

      # show all installed Cypress versions
      - run: npx cypress cache path
      - run: npx cypress cache list

      - run:
          name: Start TodoMVC server
          command: npm start
          working_directory: todomvc
          background: true

      - save_cache:
          paths:
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies)
            - ~/.cache
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Cypress tests
          command: npm test
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

  # alternative:
  #   starts the app and runs tests using a single start-server-and-test command
  single-command:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - install-dependencies

      - save_cache:
          paths:
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies)
            - ~/.cache
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Start and test
          command: npm run ci

workflows:
  version: 2
  tests:
    jobs:
      - two-commands
      - single-command
